services:
  hard_nginx:
    image: nginx:alpine3.20
    container_name: hard_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - hard_php_fpm
    networks:
      - hard
  hard_php_fpm:
    build:
      context: .
  db:
    image: mariadb
    container_name: db
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: password
    networks:
      - hard

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"
    networks:
      - hard

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address ":9001" /data
    networks:
      - hard

    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html
    networks:
      - hard

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
networks:
  hard:
    driver: bridge
